apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp-ns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Camille-Sym/jenkins-live.git
    path: namespaces
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true