apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-ingress-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Camille-Sym/jenkins-live.git
    path: ingress
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true