apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-live
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Camille-Sym/jenkins-live.git
    path: argocd-apps
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../jenkins/values.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true