apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-live
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Camille-Sym/jenkins-live.git
    path: jenkins
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true